### ISSUE TITLE
pydantic.v1.error_wrappers.ValidationError: 1 validation error for DataSource

### ISSUE THREAD

**Issue by llermaly** [2sunflower33/homeai#2]
Hello, I'm trying to run this example and found some issues. 

1. When running `python main.py` got: 

> from llama_parse import LlamaParse  # pip install llama-parse
...
> ModuleNotFoundError: No module named 'llama_parse'

Then I did `poetry add llama-parse` 

And went away.

2. Now when running `python main.py` I see: 

> Traceback (most recent call last):
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/homeai/backend/main.py", line 8, in <module>
>     from app.api.routers.chat import chat_router
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/homeai/backend/app/api/routers/chat.py", line 10, in <module>
>     from llama_index.chat_engine.types import BaseChatEngine
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/homeai/backend/.venv/lib/python3.11/site-packages/llama_index/__init__.py", line 13, in <module>
>     from llama_index.callbacks.global_handlers import set_global_handler
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/homeai/backend/.venv/lib/python3.11/site-packages/llama_index/callbacks/__init__.py", line 7, in <module>
>     from .token_counting import TokenCountingHandler
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/homeai/backend/.venv/lib/python3.11/site-packages/llama_index/callbacks/token_counting.py", line 6, in <module>
>     from llama_index.utilities.token_counting import TokenCounter
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/homeai/backend/.venv/lib/python3.11/site-packages/llama_index/utilities/token_counting.py", line 6, in <module>
>     from llama_index.llms import ChatMessage, MessageRole
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/homeai/backend/.venv/lib/python3.11/site-packages/llama_index/llms/__init__.py", line 1, in <module>
>     from llama_index.core.llms.types import (
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/homeai/backend/.venv/lib/python3.11/site-packages/llama_index/core/__init__.py", line 19, in <module>
>     from llama_index.core.indices import (
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/homeai/backend/.venv/lib/python3.11/site-packages/llama_index/core/indices/__init__.py", line 4, in <module>
>     from llama_index.core.indices.composability.graph import ComposableGraph
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/homeai/backend/.venv/lib/python3.11/site-packages/llama_index/core/indices/composability/__init__.py", line 4, in <module>
>     from llama_index.core.indices.composability.graph import ComposableGraph
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/homeai/backend/.venv/lib/python3.11/site-packages/llama_index/core/indices/composability/graph.py", line 7, in <module>
>     from llama_index.core.indices.base import BaseIndex
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/homeai/backend/.venv/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 12, in <module>
>     from llama_index.core.ingestion import run_transformations
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/homeai/backend/.venv/lib/python3.11/site-packages/llama_index/core/ingestion/__init__.py", line 2, in <module>
>     from llama_index.core.ingestion.pipeline import (
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/homeai/backend/.venv/lib/python3.11/site-packages/llama_index/core/ingestion/pipeline.py", line 31, in <module>
>     from llama_index.core.ingestion.api_utils import get_client
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/homeai/backend/.venv/lib/python3.11/site-packages/llama_index/core/ingestion/api_utils.py", line 20, in <module>
>     from llama_index.core.ingestion.data_sources import (
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/homeai/backend/.venv/lib/python3.11/site-packages/llama_index/core/ingestion/data_sources.py", line 436, in <module>
>     ConfigurableDataSources = build_configurable_data_source_enum()
>                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/homeai/backend/.venv/lib/python3.11/site-packages/llama_index/core/ingestion/data_sources.py", line 117, in build_configurable_data_source_enum
>     DataSource(
>   File "/Users/gustavollermalylarrain/Documents/proyectos/labs/homeai/backend/.venv/lib/python3.11/site-packages/pydantic/v1/main.py", line 341, in __init__
>     raise validation_error
> pydantic.v1.error_wrappers.ValidationError: 1 validation error for DataSource
> component_type
>   subclass of BaseComponent expected (type=type_error.subclass; expected_class=BaseComponent)

Thanks

**Comment by TengHoo3** [comment]
Running into the same issue - any fixes here?

**Comment by TengHoo3** [comment]
If anyone has any issues here please ping me - I have the working version
